import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated; create publication supabase_realtime;`);
await db.exec(readFileSync('supabase/migrations/202609280001_school_journal.sql','utf8').replace(/^\uFEFF/,''));
const ids=[1,2,3,4].map(n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`);
for(const id of ids)await db.query('insert into auth.users(id) values($1)',[id]);
await db.query("update public.profiles set role='teacher' where id=$1",[ids[0]]);
await db.query("insert into classrooms(id,name,teacher_id) values('10000000-0000-4000-8000-000000000001','5학년 1반',$1)",[ids[0]]);
await db.query("update profiles set class_id='10000000-0000-4000-8000-000000000001' where id=$1",[ids[1]]);
const as=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated')};
const rpc=async(payload=null)=>(await db.query('select journal_request($1::jsonb) as result',[payload===null?null:JSON.stringify(payload)])).rows[0].result;
const reject=async(fn,pattern)=>assert.rejects(fn,pattern);
await as(ids[1]);assert.equal((await rpc()).version,0);
await reject(()=>rpc({action:'save',version:0,entry:{}}),/서두/);
let snapshot=await rpc({action:'start',version:0});assert.equal(snapshot.data.intro,true);
const entry={day:1,date:'1999-01-01',answers:['친구가 도와줘서 고마워요.','',''],activity:'hidden',read:true,done:true,revision:0};
snapshot=await rpc({action:'save',version:1,entry});assert.equal(snapshot.version,2);assert.equal(snapshot.data.entries[0].activity,'');assert.equal(snapshot.data.entries[0].read,false);assert.notEqual(snapshot.data.entries[0].date,entry.date);
await reject(()=>rpc({action:'save',version:1,entry}),/다른 창/);
await reject(()=>rpc({action:'save',version:2,entry:{...entry,day:2}}),/내일/);
await reject(()=>rpc({action:'save',version:2,entry:{...entry,revision:1,answers:['  ','',''],done:false}}),/한 줄/);
await reject(()=>rpc({action:'save',version:2,entry:{...entry,revision:1,answers:['x'.repeat(2001),'','']}}),/2,000/);
await reject(()=>rpc({action:'save',version:2,entry:{...entry,day:1.2}}),/기록일/);
await reject(()=>db.query("update profiles set role='teacher' where id=$1",[ids[1]]),/permission denied/);
await reject(()=>db.query("update journal_state set version=99"),/permission denied/);
await as(ids[2]);assert.equal((await db.query('select * from journal_state')).rows.length,0);assert.equal((await db.query('select * from profiles')).rows.length,1);assert.deepEqual((await db.query('select teacher_students() as value')).rows[0].value,[]);
await rpc({action:'start',version:0});
await as(ids[0]);assert.equal((await db.query('select * from journal_state')).rows.length,1);const students=(await db.query('select teacher_students() as value')).rows[0].value;assert.equal(students.length,1);assert.equal(students[0].id,ids[1]);await reject(()=>rpc(),/학생 계정/);
await db.exec('reset role');await db.query("update profiles set role='teacher' where id=$1",[ids[3]]);await as(ids[3]);assert.equal((await db.query('select * from journal_state')).rows.length,0);
await db.exec('reset role; set role anon');await reject(()=>rpc(),/permission denied/);await reject(()=>db.query('select * from journal_state'),/permission denied/);
await db.exec('reset role');
// Move the student out of a class: the old teacher immediately loses SQL access.
await db.query('update profiles set class_id=null where id=$1',[ids[1]]);await as(ids[0]);assert.deepEqual((await db.query('select teacher_students() as value')).rows[0].value,[]);
await db.close();console.log('PASS: migration, account isolation, teacher class scope, no role escalation, anonymous denial, Seoul date, daily limit, revisions, empty/long inputs');
