"use client";
import {journalRequest} from './supabase';
import {useState,useEffect,useRef} from 'react';
import {BookOpen,ArrowRight,Sparkles,Heart,Sprout,Check,CheckCircle2,PencilLine,NotebookPen,Library,Compass,ArrowLeft,Save,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {stages,lessons,stageFor,stageDay,lessonFor,titleFor,type Entry} from './content';
type Snapshot={data:{intro:boolean;entries:Entry[]};version:number;today:string};
const blank=(day:number,date:string):Entry=>({day,date,answers:Array(stages[stageFor(day)-1].questions.length).fill(''),activity:'',read:false,done:false,revision:0});
export default function Journal({demo=false}:{demo?:boolean}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('write'),[intro,setIntro]=useState(true),[preview,setPreview]=useState(false),[demoDay,setDemoDay]=useState(32),[selected,setSelected]=useState<number|null>(null),[drafts,setDrafts]=useState<Record<string,Entry>>({}),[dirty,setDirty]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(''),[lessonIndex,setLessonIndex]=useState<number|null>(null),[about,setAbout]=useState(false);
 const firstLoad=useRef(true);const requestBusy=useRef(false);
 const entries=snapshot?.data.entries??[];const count=entries.filter(e=>e.done).length;const today=snapshot?.today??'';const todayEntry=entries.find(e=>e.date===today&&e.done);const activeDay=todayEntry?.day??count+1;
 const day=preview?demoDay:selected??activeDay;const stage=stageFor(day),localDay=stageDay(day),info=stages[stage-1],lesson=lessonFor(day);const key=(preview?'preview-':'day-')+day;
 const entry=drafts[key]??entries.find(e=>!preview&&e.day===day)??blank(day,today);const currentDirty=!!dirty[key];
 const hasUnsaved=Object.values(dirty).some(Boolean);
 async function load(){if(demo){setSnapshot({data:{intro:false,entries:[]},version:0,today:''});setLoading(false);return}setLoading(true);setError('');try{const j=await journalRequest() as Snapshot;setSnapshot(j);if(firstLoad.current){setIntro(!j.data.intro);firstLoad.current=false;}}catch(e){setError(e instanceof Error?e.message:'기록을 불러오지 못했어요.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!hasUnsaved)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[hasUnsaved]);
 // Refresh the date when returning to the tab; drafts remain untouched.
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&!requestBusy.current)void load()};document.addEventListener('visibilitychange',refresh);return()=>document.removeEventListener('visibilitychange',refresh)},[]);
 function edit(patch:Partial<Entry>){setDrafts(d=>({...d,[key]:{...entry,...patch}}));setDirty(d=>({...d,[key]:true}));setMessage('')}
 async function mutate(body:object){if(requestBusy.current)throw new Error('저장 중이에요. 잠시 기다려 주세요.');requestBusy.current=true;setBusy(true);setError('');try{const j=await journalRequest({...body,version:snapshot?.version??0}) as Snapshot;setSnapshot(j);return j as Snapshot}finally{requestBusy.current=false;setBusy(false)}}
 async function start(){if(demo){openPreview(1);return}try{await mutate({action:'start'});setIntro(false);setSelected(null);setTab('write')}catch(e){setError((e as Error).message)}}
 async function save(done:boolean){if(done&&!entry.answers.some(s=>s.trim())){setError('오늘의 마음을 한 줄 이상 적어 주세요.');return}if(preview){setDrafts(d=>({...d,[key]:{...entry,done}}));setDirty(d=>({...d,[key]:false}));setMessage('체험을 마쳤어요. 둘러보기의 글은 실제 일기장에 저장되지 않아요.');return}try{const j=await mutate({action:'save',entry:{...entry,done:done||entry.done}});const saved=j.data.entries.find(e=>e.day===day)!;setDrafts(d=>({...d,[key]:saved}));setDirty(d=>({...d,[key]:false}));setMessage(saved.done?'오늘의 마음을 소중히 담았어요. 내일 또 만나요!':'작성 중인 글을 저장했어요. 나중에 이어 써도 괜찮아요.')}catch(e){setError((e as Error).message)}}
 function openPreview(n:number){setDemoDay(n);setPreview(true);setIntro(false);setTab('write');setMessage('');setError('')}
 function goToday(){if(demo){setIntro(true);setPreview(false);setTab('write');return}setPreview(false);setSelected(null);setIntro(!snapshot?.data.intro);setTab('write');setMessage('')}
 useEffect(()=>{type MC={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const ctx=(document as Document&{modelContext?:MC}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'preview_gratitude_day',description:'Open a curriculum day in non-saving preview mode; does not advance real progress.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:1,maximum:100000}},required:['day'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const n=(input as {day?:number})?.day;if(!Number.isInteger(n)||n!<1||n!>100000)throw new Error('day must be an integer from 1 to 100000');openPreview(n!);return {day:n,stage:stageFor(n!),stageDay:stageDay(n!),hasActivity:!!lessonFor(n!),mode:'preview'}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 return <><header className="topbar"><button className="brand" onClick={goToday}><span className="brand-icon"><Sprout size={24}/></span>마음 한 줄 <span className="brand-sub">감사일기</span></button><span className="small">나를 위한 작은 기록</span></header><main className="shell"><div className="page-heading"><div><span className="eyebrow">나의 감사 여행</span><h1>{tab==='history'?'차곡차곡 모인 나의 마음':tab==='library'?'읽고, 생각하고, 마음을 나눠요':intro?'작은 고마움을 발견하는 시간':'오늘, 어떤 순간을 만났나요?'}</h1><p>{intro?'하루 한 줄부터, 내 속도에 맞춰 시작해요.':`${count}일의 마음을 담았어요. 쉬어 가도 괜찮아요.`}</p></div><button className="text-button" onClick={()=>openPreview(32)}><Compass size={18}/>전체 과정 둘러보기</button></div>
 <Tabs value={tab} onValueChange={v=>{setTab(v);setMessage('')}} className="main-tabs"><TabsList aria-label="감사일기 메뉴" className="nav-tabs"><TabsTrigger value="write"><PencilLine size={17}/>오늘의 일기</TabsTrigger><TabsTrigger value="history"><NotebookPen size={17}/>나의 일기장</TabsTrigger><TabsTrigger value="library"><Library size={17}/>읽기와 활동</TabsTrigger></TabsList></Tabs>
 {error&&<div className="notice error" role="alert"><span>{error}</span><button className="text-button" onClick={()=>void load()}>다시 불러오기</button></div>}
 {preview&&tab==='write'&&<div className="preview-box"><div><strong><Compass size={18}/>전체 과정 둘러보기</strong><p>어느 단계든 미리 체험해요. 실제 기록과 진도는 바뀌지 않아요.</p></div><div className="preview-days">{[1,14,15,28,29,32,36].map(n=><button className={day===n?'chosen':''} key={n} onClick={()=>openPreview(n)}>{n}일</button>)}<label>다른 기록일<input aria-label="둘러볼 기록일" type="number" min={1} max={100000} value={demoDay} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=100000)setDemoDay(n)}}/></label><button className="text-button" onClick={goToday}>내 일기로 돌아가기</button></div></div>}
 {tab==='write'?<div className="workspace"><aside className="journey" aria-label="감사일기 단계"><p className="eyebrow">우리의 여정</p>{['서두 · 시작하기',...stages.map((s,i)=>`${i+1}단계 ${s.name}`)].map((s,i)=><div className={'journey-item '+(i===(intro?0:stage)?'active':'')} key={s}><span className="step-number">{i===0?<BookOpen size={18}/>:count>=i*14&&i<3?<Check size={16}/>:i}</span><div><strong>{s}</strong><small>{['감사일기를 만나 봐요','14일 · 작은 순간 발견하기','14일 · 소중한 이유 찾기','계속 · 일상에서 마음 전하기'][i]}</small></div></div>)}<div className="gentle"><Heart size={20}/><p>멋진 문장이 아니어도 괜찮아.<br/>네 마음이면 충분해.</p>{!intro&&<button className="text-button" onClick={()=>{setIntro(true);setPreview(false)}}>서두 다시 읽기</button>}</div></aside>
 <section className={'paper stage-'+(intro?1:stage)}>{intro?<><span className="pill">서두 · 시작하기</span><h2>감사는 어떤 마음일까요?</h2><p className="lead">친구가 건넨 다정한 말, 맛있게 먹은 점심, 창문으로 들어온 시원한 바람. 우리 곁에는 작지만 고마운 순간이 있어요.</p><div className="intro-note"><Sparkles size={23}/><div><h3>당연하게 여겼던 것을 새롭게 보기</h3><p>감사일기는 내 하루에서 고마운 일을 찾아 적는 기록이에요. 아주 특별한 일이 아니어도 좋아요. 무엇이 나에게 힘이 되었는지 함께 찾아봐요.</p></div></div><div className="intro-rules"><div><b>01</b><h3>솔직하게 써요</h3><p>속상한 마음을 숨기거나 억지로 감사할 필요는 없어요.</p></div><div><b>02</b><h3>짧아도 괜찮아요</h3><p>정답도, 점수도 없어요. 나만의 말로 한 줄부터 써요.</p></div><div><b>03</b><h3>내 속도로 가요</h3><p>하루 쉬어도 괜찮아요. 다시 이어 쓰면 돼요.</p></div></div><details className="more"><summary>어떻게 이어 가나요?</summary><p>1단계는 14일 동안 하루를 살펴보고, 2단계는 14일 동안 고마운 이유를 생각해요. 3단계부터는 끝나는 날 없이 계속 써요. 3단계의 4·8·12일째처럼 4일마다 읽기와 활동을 만나요.</p><p>날짜가 아니라 <strong>일기를 마친 날</strong>을 세어요. 하루에 한 기록일씩 진행하며, 쉬는 날에는 진도가 줄어들지 않아요. 활동은 나중에 다시 해도 좋아요.</p></details><div className="paper-bottom"><span className="small">하루 5분, 나를 돌보는 시간</span><button className="primary" disabled={busy||loading||!snapshot} onClick={()=>snapshot?.data.intro?setIntro(false):void start()}>{snapshot?.data.intro?'일기 이어 쓰기':'첫 번째 발견 시작하기'}<ArrowRight size={18}/></button></div></>:<>
 <div className="entry-top"><span className="pill">{stage}단계 · {localDay}일째{stage<3?' / 14일':''}</span><span className="small">{preview?'둘러보기':entry.date||today} · 전체 {day}일째</span></div><h2>{titleFor(day)}</h2><p className="lead">{info.intro}</p>{stage<3&&<div className="stage-progress"><Progress value={(Math.max(0,Math.min(count-(stage===2?14:0),14))/14)*100} aria-label={`${stage}단계 진행률`}/><span>{Math.max(0,Math.min(count-(stage===2?14:0),14))} / 14일 완료</span></div>}
 {entry.done&&!currentDirty&&!preview&&<div className="saved-banner"><CheckCircle2 size={21}/><span>이 날의 일기를 마쳤어요. 내용을 고쳐서 다시 저장할 수 있어요.{day===14?' 다음 기록일부터 2단계가 시작돼요.':day===28?' 다음 기록일부터 3단계가 시작돼요.':''}</span></div>}
 <form onSubmit={e=>{e.preventDefault();void save(true)}}><fieldset disabled={busy} className="entry-fields">{info.questions.map((q,i)=><label className="question" key={`${stage}-${i}`}><span className="question-title"><span className="question-number">{i+1}</span>{q}</span><span className="help">{info.helps[i]}</span><textarea aria-label={q} maxLength={2000} value={entry.answers[i]??''} placeholder={'예) '+info.examples[i]} onChange={e=>{const a=[...entry.answers];a[i]=e.target.value;edit({answers:a})}}/><span className="char-count">{(entry.answers[i]??'').length} / 2,000</span></label>)}
 {stage===3&&(lesson?<section className="activity-card"><div className="activity-header"><BookOpen size={22}/><div><span className="eyebrow">4일마다 만나는 마음 쉼터</span><h3>오늘은 읽고, 함께 해 보는 날</h3></div></div><span className="small">{lesson.round>1?`${lesson.round}번째 다시 만나기 · 새로운 경험으로 해 봐요`:'읽기와 활동 · 약 5~10분'}</span><article className="reading"><span className="reading-label">읽기자료</span><h3>{lesson.title}</h3>{lesson.body.map(p=><p key={p}>{p}</p>)}</article><label className="check-label"><Checkbox checked={entry.read} onCheckedChange={v=>edit({read:v===true})}/>읽기자료를 읽었어요</label><div className="activity-task"><span className="reading-label">활동자료</span><h3>{lesson.activity}</h3><ol>{lesson.steps.map(s=><li key={s}>{s}</li>)}</ol><label className="question">{lesson.prompt}<textarea aria-label="활동 기록" maxLength={4000} value={entry.activity} onChange={e=>edit({activity:e.target.value})} placeholder="내 생각을 자유롭게 적어 보세요. 활동은 나중에 이어 해도 좋아요."/></label>{lesson.note&&<p className="small">{lesson.note}</p>}<span className="source-note">원문 PDF {lesson.pages}쪽 바탕 · 쉬운 말로 재구성</span></div></section>:<div className="next-activity"><BookOpen size={20}/><p>다음 읽기와 활동은 <strong>3단계 {Math.ceil(localDay/4)*4}일째</strong>에 만나요.</p></div>)}
 <div className="paper-bottom"><div className="small">{currentDirty?'아직 저장하지 않은 내용이 있어요.':preview?'둘러보기의 글은 실제로 저장되지 않아요.':'저장한 글은 작성 중인 글도 담당 선생님이 볼 수 있어요.'}</div><div className="save-actions"><button type="button" className="secondary" disabled={!preview&&(!snapshot||loading)} onClick={()=>void save(false)}><Save size={16}/>이어 쓸 글 저장</button><button type="submit" className="primary" disabled={!preview&&(!snapshot||loading)}>{busy?'저장하는 중…':preview?'체험 마치기':entry.done?'수정한 일기 저장':'오늘의 일기 마치기'}<Check size={18}/></button></div></div></fieldset></form>{message&&<div className="notice success" role="status"><CheckCircle2 size={20}/>{message}</div>}{selected!==null&&!preview&&<button className="text-button back-button" onClick={goToday}><ArrowLeft size={16}/>오늘의 일기로 돌아가기</button>}<p className="source-note">{info.source} 바탕 · 질문과 예시를 초등학생에 맞게 재구성</p></>}</section></div>:tab==='history'?<section className="paper collection"><span className="pill">나의 일기장</span><h2>{count}일의 고마운 순간</h2><p className="lead">저장한 기록을 다시 읽거나 이어 쓸 수 있어요.</p>{loading?<p role="status">일기장을 불러오는 중이에요…</p>:entries.length===0?<div className="empty-state"><NotebookPen size={40}/><h3>첫 번째 이야기를 기다리고 있어요</h3><p>작은 순간 하나를 담으면 이곳에 차곡차곡 모여요.</p><button className="primary" onClick={goToday}>오늘의 일기 쓰기<ArrowRight size={17}/></button></div>:<div className="entry-list">{[...entries].reverse().map(e=><button key={e.day} className="entry-row" onClick={()=>{setSelected(e.day);setPreview(false);setIntro(false);setTab('write');setMessage('')}}><span className="entry-day">{String(e.day).padStart(2,'0')}</span><span><span className="small">{e.date} · {stageFor(e.day)}단계 · {e.done?'완료':'작성 중'}</span><strong>{e.answers.find(s=>s.trim())||'이어서 작성해 보세요.'}</strong></span><ChevronRight size={20}/></button>)}</div>}</section>:<section className="paper collection"><span className="pill">읽기와 활동</span><h2>고마운 마음을 조금 더 깊게</h2><p className="lead">3단계에서 4일마다 읽기자료와 활동자료를 함께 만나요. 11가지 묶음을 모두 만나면, 새로운 경험으로 다시 연습해요.</p><div className="lesson-grid">{lessons.map((l,i)=><button key={l.title} className="lesson-tile" onClick={()=>setLessonIndex(i)}><span className="lesson-number">{String(i+1).padStart(2,'0')}</span><span className="small">3단계 {(i+1)*4}일째</span><h3>{l.title}</h3><p>{l.activity}</p><span className="tile-link">읽기와 활동 열기<ArrowRight size={16}/></span></button>)}</div></section>}
 </main><footer><span>마음 한 줄 · 나만의 속도로 이어 가요.</span><button className="text-button" onClick={()=>setAbout(true)}>자료와 이용 안내</button></footer>
 <Dialog open={lessonIndex!==null} onOpenChange={o=>{if(!o)setLessonIndex(null)}}><DialogContent className="lesson-dialog"><DialogHeader><DialogTitle>{lessonIndex!==null?lessons[lessonIndex].title:''}</DialogTitle><DialogDescription>읽기자료와 활동자료 · 초등학생을 위한 쉬운 말 풀이</DialogDescription></DialogHeader>{lessonIndex!==null&&<><div className="reading">{lessons[lessonIndex].body.map(p=><p key={p}>{p}</p>)}</div><h3>{lessons[lessonIndex].activity}</h3><ol className="activity-steps">{lessons[lessonIndex].steps.map(p=><li key={p}>{p}</li>)}</ol><p className="intro-note">{lessons[lessonIndex].prompt}</p>{lessons[lessonIndex].note&&<p className="small">{lessons[lessonIndex].note}</p>}<p className="source-note">원문 PDF {lessons[lessonIndex].pages}쪽 바탕 · 요약·재구성</p><button className="primary" onClick={()=>{openPreview(28+(lessonIndex+1)*4);setLessonIndex(null)}}>이 활동 체험하기<ArrowRight size={17}/></button></>}</DialogContent></Dialog>
 <Dialog open={about} onOpenChange={setAbout}><DialogContent className="lesson-dialog"><DialogHeader><DialogTitle>자료와 이용 안내</DialogTitle><DialogDescription>선생님이 검토할 첫 번째 버전이에요.</DialogDescription></DialogHeader><h3>자료의 바탕</h3><p>사용자가 제공한 「감사일기 병합.pdf」의 Kurzgesagt Gratitude Journal을 바탕으로 만들었어요. 원문 전체의 문장별 번역이 아니라, 서두·세 단계 질문·읽기·활동을 초등학교 5학년 수준으로 풀어 쓴 요약·재구성본이에요.</p><h3>수업에 맞춘 구성</h3><p>1·2단계 각 14일, 3단계 매 4일 활동 주기는 선생님의 요청을 반영했어요. 하루에 한 기록일씩 진행하고 빠진 날은 세지 않아요. 읽기와 활동 11묶음은 44일마다 순환해요.</p><h3>기록 저장</h3><p>저장 버튼을 누른 기록은 로그인한 계정의 일기장에 저장돼요. 자동 저장은 아니에요. 저장한 글은 작성 중인 글도 담당 선생님이 볼 수 있어요. 다른 학생은 내 일기를 볼 수 없어요. 공용 기기에서는 사용 후 꼭 로그아웃해 주세요. 둘러보기에서 쓴 글은 실제 일기장에 저장되지 않아요.</p><h3>마음 편하게 쓰기</h3><p>불편한 경험을 억지로 감사로 바꾸지 않아도 괜찮아요. 이름·주소 같은 자세한 개인정보는 쓰지 않아도 돼요. 편지는 작성만 하며 자동으로 전송되지 않아요.</p></DialogContent></Dialog>
 </>;
}
