"use client";
import {useEffect,useState,useCallback} from 'react';
import {getSupabase} from './supabase';
import {type Profile} from './school-app';
import {type Entry,stages,stageFor,lessonFor} from './content';
type Classroom={id:string;name:string};
type Student={id:string;display_name:string;class_id:string;data:{intro:boolean;entries:Entry[]};updated_at:string|null};
export default function Teacher({profile}:{profile:Profile}){
 const [classes,setClasses]=useState<Classroom[]>([]),[classId,setClassId]=useState(''),[students,setStudents]=useState<Student[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[status,setStatus]=useState('연결 중'),[updated,setUpdated]=useState('');
 const load=useCallback(async()=>{try{const client=await getSupabase();const [c,s]=await Promise.all([client.from('classrooms').select('id,name').order('name'),client.rpc('teacher_students')]);if(c.error||s.error)throw new Error('학급 기록을 불러오지 못했어요. 다시 시도해 주세요.');setClasses(c.data??[]);setStudents(s.data??[]);setError('');setUpdated(new Date().toLocaleTimeString('ko-KR'));}catch(e){setStudents([]);setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{let active=true;let cleanup=()=>{};void load();getSupabase().then(client=>{if(!active)return;const refresh=()=>{if(active)void load()};const channel=client.channel('teacher-'+profile.id).on('postgres_changes',{event:'*',schema:'public',table:'journal_state'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'profiles'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'classrooms'},refresh).subscribe(s=>{if(!active)return;setStatus(s==='SUBSCRIBED'?'실시간 연결됨':'다시 연결 중 · 30초마다 확인');if(s==='SUBSCRIBED')refresh()});const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);cleanup=()=>{clearInterval(timer);window.removeEventListener('focus',refresh);void client.removeChannel(channel)}});return()=>{active=false;cleanup()}},[load,profile.id]);
 const visible=students.filter(s=>!classId||s.class_id===classId),student=visible.find(s=>s.id===selected),entries=student?.data.entries??[];
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 return <><header className="topbar"><strong className="brand">마음 한 줄 <span className="brand-sub">교실</span></strong><span className="small" role="status">{status}</span></header><main className="shell teacher-shell"><div className="page-heading"><div><span className="eyebrow">선생님의 일기장</span><h1>우리 반의 고마운 순간</h1><p>학생이 저장한 글과 진도를 확인해요. 작성 중 저장한 글도 표시됩니다.</p></div><button className="secondary" onClick={()=>void load()}>새로고침</button></div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="teacher-toolbar"><label>학급 <select value={classId} onChange={e=>{setClassId(e.target.value);setSelected('')}}><option value="">담당 학급 전체</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><span>학생 {visible.length}명 · 오늘 완료 {visible.filter(s=>s.data.entries.some(e=>e.done&&e.date===today)).length}명</span><span className="small">{updated&&`${updated} 확인`}</span></div>{loading?<p role="status">학급을 불러오는 중이에요…</p>:<div className="teacher-grid"><section className="paper student-list" aria-label="학생 목록">{visible.length===0?<p>등록된 학생이 없습니다. Supabase에서 담당 학급과 학생 계정을 배정해 주세요.</p>:visible.map(s=>{const count=s.data.entries.filter(e=>e.done).length;return <button key={s.id} className={'student-row '+(s.id===selected?'chosen':'')} onClick={()=>setSelected(s.id)}><strong>{s.display_name}</strong><span className="small">{classes.find(c=>c.id===s.class_id)?.name} · {count}일 완료</span><span className="small">{s.updated_at?'최근 저장 '+new Date(s.updated_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 기록이 없어요'}</span></button>})}</section><section className="paper student-detail">{!student?<div className="empty-state"><h2>학생의 이야기를 만나 보세요</h2><p>학생 이름을 누르면 저장한 일기를 볼 수 있어요.</p></div>:<><span className="pill">학생 기록</span><h2>{student.display_name}의 일기장</h2>{entries.length===0?<p>아직 저장한 일기가 없어요.</p>:[...entries].reverse().map(e=><details className="teacher-entry" key={e.day}><summary>{e.day}일째 · {e.date} · {stageFor(e.day)}단계 · {e.done?'완료':'작성 중'}</summary>{e.answers.map((answer,i)=><div key={i}><h3>{stages[stageFor(e.day)-1].questions[i]}</h3><p className="student-answer">{answer||'아직 쓰지 않았어요.'}</p></div>)}{lessonFor(e.day)&&<><h3>{lessonFor(e.day)?.title}</h3><p>읽기: {e.read?'읽었어요':'아직이에요'}</p><p className="student-answer">{e.activity||'활동 기록이 없어요.'}</p></>}</details>)}</>}</section></div>}</main></>;
}
